spring.application.name=shopsphere

spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere
spring.datasource.username=root
spring.datasource.password=MGbrothers

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
